sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  minio:
      # MinIO 服务地址（你本地启动的）
      endpoint: http://127.0.0.1:9000
      # 账号
      access-key-id: minioadmin
      # 密码
      access-key-secret: minioadmin
      # 默认桶名称（可以自己改）
      bucket-name: sky-picture
  wechat:
    appid: wxfb4b925b2159168b
    secret: 2a4a604842ce57825c7ebfa652a6a83b
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10